### ISSUE TITLE
NFR: Configure analytics/tracking

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-co#7]
Configure analytics/tracking (GTM, FB Pixel if needed, and OneTrust)

This is part of the GoLive activities.

**Comment by Kannan-CM** [comment]
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="119d1cfa-158d-4685-86ac-7a29c9c4dca0" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>

**Comment by Kannan-CM** [comment]
<button id="ot-sdk-btn" class="ot-sdk-show-settings">Cookie Settings</button>
